### ISSUE TITLE
listen_unix Small bug

### ISSUE THREAD

**Issue by iam-Justin** [go-siris/siris#20]
still output **Now listening on: http://localhost:8080**

**Comment by Dexus** [comment]
can you please provide an example to reproduce?

**Comment by iam-Justin** [comment]
example
https://github.com/go-siris/siris/blob/master/_examples/beginner/listening/listen-unix/main.go

**Comment by Dexus** [comment]
It's not a BUG... as of UNIX listener have no (addr/) hostname in the config after start, the default will be used.
We can not check what kind of listener is used, so we can't change this output with unix sockets.
