### ISSUE TITLE
Websocket examples

### ISSUE THREAD

**Issue by Dexus** [go-siris/siris#21]
https://github.com/go-siris/siris/blob/master/_examples/intermediate/websockets/connectionlist/main.go#L73

Need to be close (`delete(Conn,c)`) the connection, else you get all the message...

**Comment by Andersbiha** [comment]
Isn't this exactly what is supposed to happen?

Since you're leaving a room and not totally disconnecting the web-socket connection should still be kept alive.

**Comment by Dexus** [comment]
yeah, I was first thinking that was the bug, but it must a bit deeper in the source. Maybe you can find it if you like to watch into it. Else I will do it later.

**Comment by Andersbiha** [comment]
Il'l look into it when i get off work.

**Comment by Dexus** [comment]
To fix this bug we need to change only:

https://github.com/go-siris/siris/blob/master/websocket/emitter.go#L47 add this
```
if e.conn.server.rooms[e.to] == nil {
	return nil
}

```
https://github.com/go-siris/siris/blob/master/websocket/server.go#L304-305
```
s.rooms[name] = append(s.rooms[name][:i], s.rooms[name][i+1:]...)
```

https://github.com/go-siris/siris/blob/master/websocket/server.go#L331-332
```
s.rooms[roomName] = append(s.rooms[roomName][:i], s.rooms[roomName][i+1:]...)
```

Sorry if I just steal you the fun to look into it 😀

**Comment by Andersbiha** [comment]
Should be fixed in the latest commit to the devel branch https://github.com/go-siris/siris/commit/c5fd6787fba149bb5e20fb69fc4e8828db866370
