### ISSUE TITLE
Windows 10 socket TCP socket issue

### ISSUE THREAD

**Issue by Allendar** [go-siris/siris#28]
OS: Windows 10
Go: 1.8.3 64bit
Siris: 7.3.0

A friend of mine is trying to help me with my project and he's on Windows. Suddenly since the transfer from Iris to Siris he gets the following error:

```
.../github.com/go-siris/siris/vendor/gopkg.in/go-siris/tcplisten.v1
vendor\github.com\go-siris\siris\vendor\gopkg.in\go-siris\tcplisten.v1\socket.go:22: cannot use fd (type syscall.Handle) as type int in return argument
```

He temporarily hard-edited the file to return `1, nil` instead of `fd, nil` and that works.

Maybe it has to do something with these old threads?

https://groups.google.com/forum/#!msg/golang-dev/_ITOGl9eoxQ/Gj0kITirqmEJ
https://codereview.appspot.com/4600042/

**Comment by Dexus** [comment]
Please update to siris 7.3.4

Von meinem iPhone gesendet

**Comment by Allendar** [comment]
He tried `7.3.3` (latest release), but still the same error. I sadly don't have a Windows machine near me to test.

**Comment by Dexus** [comment]
I try to find the issue, i make now a clean install and come back to this issue.

**Comment by Dexus** [comment]
Please try to update to the last siris v7.3.4

**Comment by Goosterhof** [comment]
I updated to last version and it works!

**Comment by Dexus** [comment]
So we can close here?

**Comment by Goosterhof** [comment]
yeah, thnx for the fix!
