### ISSUE TITLE
Multiple fields [GET params]

### ISSUE THREAD

**Issue by everton-sales-branco** [go-siris/siris#29]
Hi guys,
To get values in a query of GET method, like:
"?searchPhrase[fields][]=name&searchPhrase[fields][]=registry&test=abc"

I did something like this:
ctx.Request.Form["searchPhrase[fields][]"][0]   -> name
ctx.Request.Form["searchPhrase[fields][]"][1]   -> registry

I think is a good idea do some wrapper to that, I right?

**Comment by Dexus** [comment]
You can use a struct for it.

Von meinem iPhone gesendet

**Comment by everton-sales-branco** [comment]
@Dexus Is there any function to it?

**Comment by Dexus** [comment]
I mean yes but I have just no computer to look. I mean there is also an example or maybe it was on the iris website as long as it was available...

Von meinem iPhone gesendet

**Comment by Allendar** [comment]
I never used it, but I think it was something like this:

```go
type FormObject struct {
	Username string `form:"username"`
	Password string `form:"password"`
}

func yourRouteFunction(c context.Context) {
	form := &FormObject{}
	c.ReadForm(form)
}
```

**Comment by Dexus** [comment]
Try this: https://github.com/google/go-querystring/issues/7#issuecomment-259792233

It's not yet for GET Params (Querystring) implemented if looked just into it. But we can do it.

**Comment by Dexus** [comment]
Or even better maybe: https://github.com/pasztorpisti/qs

**Comment by EvertonSalesBranco** [comment]
@Dexus https://github.com/pasztorpisti/qs is a good alternative, maybe it should be incorporated in the project.

**Comment by Dexus** [comment]
When you use ctx.Request.URL.Query() and qs or schema you don't need to build this crap wrapper...

**Comment by everton-sales-branco** [comment]
Ok, qs is the solution.

**Comment by Dexus** [comment]
Internal notice:
- https://github.com/pasztorpisti/qs
- https://github.com/gorilla/schema

Add a new context function for get params to parse into a struct. Also add a shortcut function to get fields only for querystrings, because `ctx.request.Form`  (`ctx.FormValue('namestring')` or `ctx.FormValues()`) overwrite same name fields with post/put params.
