### ISSUE TITLE
real-ip only via enabled config *security

### ISSUE THREAD

**Issue by Dexus** [go-siris/siris#32]
Make real ip headers only change the remoteAddress when the config is set else visitors are able to fake own ip addresses...
Make config variable to enable differend types of "proxys".

**Comment by hiveminded** [comment]
Thanks for pointing that out on [that commit's comment](https://github.com/get-ion/ion/commit/70c1b92419ccdb78c3e96eb1600078d17c368831#commitcomment-22968414).

at [ion](https://github.com/get-ion/ion), an iris-based framework too, we fixed that with the following options: `WithRemoteAddrHeader/WithoutRemoteAddrHeader` that can be passed to the `app.Run`.

You're free to see the code and apply these fixes on this repo too, the commit is:  https://github.com/get-ion/ion/commit/a4e550dc37b0d27384c3b84c1015de1db4009d3b

Best regards from @get-ion !

**Comment by Dexus** [comment]
@hiveminded please note "CF-Connecting-IP" not "HTTP_CF_CONNECTING_IP" cause of real headers and not a PHP/FCGI Client or Server that change the header to UPPERCASE and prefixing the header names to prevent overwriting the environments...
