### ISSUE TITLE
Use Cache Markdown for partial data

### ISSUE THREAD

**Issue by speedwheel** [go-siris/siris#37]
#I saw that the Cache Markdown it's used for full page caching, is there any way I can use it just to store certain content from the page (key, value interface for example).

**Comment by Allendar** [comment]
You can easily write a cache yourself with a atomic-based map structure like https://github.com/orcaman/concurrent-map or https://github.com/coocood/freecache. This way you'll have 100% control on how your _block-cache_ works.

**Comment by theodesp** [comment]
Maybe we can w8 for 1.9 with sync.map https://github.com/golang/go/issues/18177 ?

**Comment by Allendar** [comment]
Closing this as it seems like a custom required feature for speedwheel's project.
