### ISSUE TITLE
Add code coverage reported via https://codecov.io

### ISSUE THREAD

**Issue by theodesp** [go-siris/siris#42]
As a contributor, and user I would like to see the projects code coverage report in a nice graphic environment

Solution
----
Utilize  https://codecov.io

See example project [here](https://github.com/codecov/example-go)

**Comment by theodesp** [comment]
https://github.com/go-siris/siris/pull/43

**Comment by theodesp** [comment]
Sample report
https://codecov.io/gh/theodesp/siris/branch/SIRIS-42

**Comment by Dexus** [comment]
Close #42 via 87aec87
