### ISSUE TITLE
Need AppVeyor Support for testing on windows clients

### ISSUE THREAD

**Issue by theodesp** [go-siris/siris#46]
**Note: for support questions, please use our [gitter channel](https://gitter.im/gosiris/siris) or stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

*   **I'm submitting a ... **

    *  [ ] bug report
    *  [x] feature request
    *  [ ] support request => Please do not submit support request here, see note at the top of this template.
*   **Do you want to request a _feature_ or report a _bug_?**
Feature
*   **What is the current behavior?**
No tests running for windows clients
*   **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 

*   **What is the expected behavior?**
Add tests running for windows clients
*   **What is the motivation / use case for changing the behavior?**
Cross platform conformance
*   **Please tell us about your environment:**

*   Library version: v7.3.4
*   Operating System: [Darwin Kernel Version 10.2.0 | Microsoft Windows [Version 10.0.10240]]
*   System Information: [Core i7-7740X 16gb Ram]

*   **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by theodesp** [comment]
PR https://github.com/go-siris/siris/pull/47

**Comment by Dexus** [comment]
Merged via 215750b6791906bea9f4aa03f11727c554b9e850
Close #47 
Close #46
