### ISSUE TITLE
Why I get the notification from this repo

### ISSUE THREAD

**Issue by astaxie** [go-siris/siris#50]
I didn't watch this repo. And got a lot notifications from this repo.

**Comment by Dexus** [comment]
Because some Git-User use the mention?
Maybe you can give some more background in which context you get the mention?

**Comment by astaxie** [comment]
No, All the issue update and pull request I will get the notifications. That's weird.

**Comment by Dexus** [comment]
Hmm, don't know. Maybe it'll be better to contact the GitHub-Support. I only know that you where used in some mentions here from a user.

I close this issue, as we are not able to fix that - it's GitHubs job.

**Comment by astaxie** [comment]
I find that this https://github.com/go-siris/siris/issues/48 mentioned me. 😓

**Comment by Dexus** [comment]
This should now stop. It's closed and locked.
Sorry.
