### ISSUE TITLE
Full server hang after setting Flash Message and redirecting

### ISSUE THREAD

**Issue by Allendar** [go-siris/siris#66]
Go 1.8.3. Homebrew
macOS Sierra 10.12.6

The following code reproduces the error. You go to `/`. Then it redirects to `/landing`. Then if you go to the `/` url again (or any that you would define), the request hangs forever.

```go
package main

import (
	"github.com/go-siris/siris"
	"github.com/go-siris/siris/context"
	"github.com/go-siris/siris/middleware/logger"
	"github.com/go-siris/siris/sessions"
)

func main() {
	app := siris.New()

	app.Use(logger.New())
	app.AttachSessionManager(sessions.New(sessions.Config{
		Cookie: "sid",
	}))

	app.Get("/", func(c context.Context) {
		c.Session().SetFlash("test", "testString")
		c.Redirect("/landing")
	})

	app.Get("/landing", func(c context.Context) {
		c.WriteString(c.Session().GetFlashString("test"))
	})

	app.Run(siris.Addr(":8085"))
}
```

**Comment by Dexus** [comment]
Do you use the master branch?

**Comment by Allendar** [comment]
No the `7.3.4` release. I'll try it on the master branch in a bit.

**Comment by Dexus** [comment]
ok, I will also look into it.

**Comment by Allendar** [comment]
Looked into together with @Dexus. Will be outphased in the next version, to use the normal Session functionality instead of the Flash helper-functions. Still a bug in the current release, but won't be anymore as it'll be deprecated in `7.4.0`.
