### ISSUE TITLE
Check if we have all required changes to make siris independent

### ISSUE THREAD

**Issue by godofdream** [go-siris/siris#7]
https://github.com/kataras/iris/pull/657/commits/c56b528dce6b4260db5e7aca7da77f25a9b5e5c3
(Sorry I see that Pullrequest is a joke)

**Comment by Dexus** [comment]
why the PR link?

**Comment by Andersbiha** [comment]
I'm wondering aswell?

**Comment by godofdream** [comment]
sorry i was sending this from a restaurant.
i will compare the changes from the PR link if we should copy some of these.

**Comment by godofdream** [comment]
I have put all the changes i had in mind into https://github.com/go-siris/siris/pull/9
